# Generated by Django 5.2.8 on 2025-11-16 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('calculo_i', 'Cálculo I'), ('logica', 'Lógica'), ('calculo_ii', 'Cálculo II'), ('introduccion_a_la_informatica', 'Introducción a la Informática'), ('estadistica_descriptiva', 'Estadística Descriptiva'), ('ingles_instrumental', 'Inglés Instrumental'), ('calculo_iii', 'Cálculo III'), ('fisica', 'Física'), ('algoritmos_y_programacion_i', 'Algoritmos y Programación I'), ('algebra', 'Álgebra'), ('inferencia_y_probabilidades', 'Inferencia y Probabilidades'), ('calculo_iv', 'Cálculo IV'), ('estructuras_discretas', 'Estructuras Discretas'), ('algoritmos_y_programacion_ii', 'Algoritmos y Programación II'), ('electronica', 'Electrónica'), ('bases_de_datos_i', 'Bases de Datos I'), ('algoritmos_y_programacion_iii', 'Algoritmos y Programación III'), ('bases_de_datos_ii', 'Bases de Datos II'), ('metodos_numericos', 'Métodos Numéricos'), ('principios_de_ingenieria_del_software', 'Principios de Ingeniería del Software'), ('arquitecturas_software', 'Arquitecturas Software'), ('metodologias_de_desarrollo_de_software', 'Metodologías de Desarrollo de Software'), ('redes_y_comunicaciones_i', 'Redes y Comunicaciones I'), ('desarrollo_de_aplicaciones_i', 'Desarrollo de Aplicaciones I'), ('redes_y_comunicaciones_ii', 'Redes y Comunicaciones II'), ('desarrollo_de_aplicaciones_ii', 'Desarrollo de Aplicaciones II')], verbose_name='Nombre de la tutoria')),
                ('description', models.TextField(verbose_name='Descripcion de la tutoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
