# Generated by Django 5.2.8 on 2026-01-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timeperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tutorship'),
        ),
    ]
