# Generated by Django 5.2.8 on 2025-11-17 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reseña', 'Reseña'), ('reserva', 'Reserva'), ('mensaje', 'Mensaje')], verbose_name='Tipo de Notificación')),
                ('body', models.TextField(verbose_name='Cuerpo de la notificación')),
                ('action_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_did_action', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_receives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
